netG:
  _target_: vc_tts_template.fastspeech2wContexts.FastSpeech2wPEProsodywoPEPCE
  max_seq_len: 4000
  num_vocab: 53
  # encoder
  encoder_hidden_dim: 256
  encoder_num_layer: 4
  encoder_num_head: 2
  conv_filter_size: 1024
  conv_kernel_size_1: 9
  conv_kernel_size_2: 1
  encoder_dropout: 0.2
  # context encoder
  peprosody_encoder_gru_dim:
  peprosody_encoder_gru_num_layer:
  shere_embedding: False
  mel_embedding_mode:
  pau_split_mode:
  # mel_emb_dim: 256
  # mel_emb_kernel: 31
  # mel_emb_dropout: 0.5
  peprosody_encoder_conv_kernel_size:
  peprosody_encoder_conv_n_layers:
  sslprosody_emb_dim: 1024
  sslprosody_layer_num: 24
  # variance predictor
  variance_predictor_filter_size: 256
  variance_predictor_kernel_size: 3
  variance_predictor_dropout: 0.5
  pitch_feature_level:
  energy_feature_level:
  pitch_quantization: "linear"
  energy_quantization: "linear"
  pitch_embed_kernel_size: 9
  pitch_embed_dropout: 0.5
  energy_embed_kernel_size: 9
  energy_embed_dropout: 0.5
  n_bins: 256
  # decoder
  decoder_hidden_dim: 256
  decoder_num_layer: 6
  decoder_num_head: 2
  decoder_dropout: 0.2
  n_mel_channel:
  # other
  encoder_fix: False
  stats:
  # stats: {"pitch_min": -0.7024055490777836, "pitch_max": 0.5050794978252391, "energy_min": -0.8127368539571762, "energy_max": 0.5676259696483612}
  # ↓ 対話相手のspeaker embなどは利用されない
  speakers: {"PAD": 0, "Teacher": 1, "MStudent": 2, "FStudent": 3}
  emotions:
  # emotions: {"PAD": 0, "Normal": 1, "Happy": 2, "Sad": 3, "Angry": 4}
  accent_info:
