netG:
  _target_: vc_tts_template.fastspeech2wVAE.FastSpeech2wVAE
  # init
  max_seq_len: 1000
  num_vocab: 53
  # encoder
  encoder_hidden_dim: 256
  encoder_num_layer: 4
  encoder_num_head: 2
  conv_filter_size: 1024
  conv_kernel_size_1: 9
  conv_kernel_size_2: 1
  encoder_dropout: 0.2
  # ref encoder
  ref_enc_dim: 512
  ref_enc_filters: [32, 32, 64, 64, 128, 128]
  ref_enc_kernel_size: 3
  ref_enc_stride: 2
  ref_enc_pad: 1
  ref_enc_gru_size: 256
  z_latent_dim: 32
  # variance predictor
  variance_predictor_filter_size: 256
  variance_predictor_kernel_size: 3
  variance_predictor_dropout: 0.5
  pitch_feature_level:
  energy_feature_level:
  pitch_quantization: "linear"
  energy_quantization: "linear"
  n_bins: 256
  # decoder
  decoder_hidden_dim: 256
  decoder_num_layer: 6
  decoder_num_head: 2
  decoder_dropout: 0.2
  # other
  n_mel_channel:
  encoder_fix: False
  stats: {"pitch_min": -0.7024055490777836, "pitch_max": 0.5050794978252391, "energy_min": -0.8127368539571762, "energy_max": 0.5676259696483612}
  speakers:
  emotions: {"Normal": 0, "Happy": 1, "Sad": 2, "Angry": 3}
  accent_info:
